// vars/deployMicroservice.groovy
def call(Map config = [:]) {

    pipeline {
        agent any

        tools {
            jdk config.jdk ?: 'jdk'      
            maven config.maven ?: 'mvn'   
        }

        stages {

            stage('Prepare Environment to EKS') {
                steps {
                    script {
                        env.IMAGE_NAME       = config.imageName ?: 'kuunyangna/myapp'
                        env.NAMESPACE        = config.namespace ?: 'default'
                        env.RELEASE          = config.helmRelease ?: env.IMAGE_NAME
                        env.BRANCH           = config.branch ?: 'main'
                        env.DOCKER_CREDS     = config.dockerCreds ?: 'docker-cred'
                        env.HELM_CHART       = config.helmChart ?: './helm-chart'
                        env.REPO_URL         = config.repoUrl ?: error("repoUrl must be provided in config")
                        env.MAVEN_PROJECT_DIR= config.mavenProjectDir ?: '.' // Maven project folder
                    }
                }
            }

            stage('Checkout') {
                steps {
                    git branch: env.BRANCH, url: env.REPO_URL
                }
            }

            stage('Build') {
                steps {
                    dir(env.MAVEN_PROJECT_DIR) {
                        sh "mvn clean package -DskipTests=false"
                    }
                }
            }

            stage('Test') {
                steps {
                    dir(env.MAVEN_PROJECT_DIR) {
                        sh "mvn test"
                    }
                }
            }

            stage('Docker Build') {
                steps {
                    dir(env.MAVEN_PROJECT_DIR) {
                        script {
                            echo "Locating shaded JAR in target/ folder..."

                            // Find the shaded JAR generated by Maven Shade plugin
                            def jarFile = sh(
                                script: "ls target/*-shaded.jar | head -n1",
                                returnStdout: true
                            ).trim()

                            if (!jarFile) {
                                error "No shaded JAR found in target/! Maven must generate a '*-shaded.jar'"
                            }

                            echo "Found JAR: ${jarFile}"

                            // Build Docker image and pass JAR as build-arg
                            sh """
                                docker build \
                                  --build-arg JAR_FILE=${jarFile} \
                                  -t ${env.IMAGE_NAME}:${env.BUILD_NUMBER} .
                            """
                        }
                    }
                }
            }

            stage('Docker Push') {
                steps {
                    withCredentials([usernamePassword(
                        credentialsId: env.DOCKER_CREDS,
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh """
                            echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                            docker push ${env.IMAGE_NAME}:${env.BUILD_NUMBER}
                        """
                    }
                }
            }

            stage('Deploy with Helm to EKS') {
                steps {
                    withCredentials([usernamePassword(
                        credentialsId: 'aws-cred',
                        usernameVariable: 'AWS_ACCESS_KEY_ID',
                        passwordVariable: 'AWS_SECRET_ACCESS_KEY'
                    )]) {
                        script {
                            sh """
                                export AWS_DEFAULT_REGION=us-east-2
                                aws eks update-kubeconfig --region us-east-2 --name aquila-cluster

                                helm upgrade --install ${env.RELEASE} ${env.HELM_CHART} \
                                  --namespace ${env.NAMESPACE} \
                                  --create-namespace \
                                  --set image.repository=${env.IMAGE_NAME} \
                                  --set image.tag=${env.BUILD_NUMBER} \
                                  --wait --timeout 5m
                            """
                        }
                    }
                }
            }

        } // end stages

        post {
            success {
                echo "Pipeline completed successfully for ${env.IMAGE_NAME}!"
            }
            failure {
                echo "Pipeline failed for ${env.IMAGE_NAME}. Check logs!"
            }
        }

    } // end pipeline
} // end call
